import type { Watch } from "./cart-context"

export const watches: Watch[] = [
  {
    id: "1",
    name: "High Quality Leather Watch",
    description: "Premium leather-strapped wristwatch with elegant gold-tone case. Water-resistant up to 50m with Japanese quartz movement.",
    price: 45000,
    originalPrice: 55000,
    image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=400&fit=crop",
    category: "Classic",
    brand: "ORON",
    inStock: true,
  },
  {
    id: "2",
    name: "Leather Scratch Watch",
    description: "Sophisticated timepiece featuring scratch-resistant sapphire crystal and genuine leather band. Perfect for formal occasions.",
    price: 52000,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop",
    category: "Classic",
    brand: "ORON",
    inStock: true,
  },
  {
    id: "3",
    name: "Leather Ultramoden Watch",
    description: "Ultra-modern design with minimalist dial and premium Italian leather strap. Features date display and luminous hands.",
    price: 48000,
    originalPrice: 60000,
    image: "https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=400&h=400&fit=crop",
    category: "Modern",
    brand: "ORON",
    inStock: true,
  },
  {
    id: "4",
    name: "High Quality Brown Leather",
    description: "Classic brown leather watch with rose gold accents. Swiss movement with 2-year warranty included.",
    price: 58000,
    image: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=400&h=400&fit=crop",
    category: "Premium",
    brand: "ORON",
    inStock: true,
  },
  {
    id: "5",
    name: "High Quality Leather Strap",
    description: "Elegant timepiece with interchangeable leather straps. Comes with black and brown options. Water-resistant.",
    price: 42000,
    originalPrice: 50000,
    image: "https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=400&h=400&fit=crop",
    category: "Classic",
    brand: "ORON",
    inStock: true,
  },
  {
    id: "6",
    name: "Beep Onyx Edition",
    description: "Limited edition onyx-faced watch with premium craftsmanship. Numbered series with certificate of authenticity.",
    price: 75000,
    image: "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=400&h=400&fit=crop",
    category: "Premium",
    brand: "ORON",
    inStock: true,
  },
  {
    id: "7",
    name: "Deep Onyx Classic",
    description: "Deep onyx dial with silver indices. Premium leather band with deployant clasp. Swiss quartz movement.",
    price: 62000,
    originalPrice: 72000,
    image: "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=400&h=400&fit=crop",
    category: "Classic",
    brand: "ORON",
    inStock: true,
  },
  {
    id: "8",
    name: "Deep Onyx Premium",
    description: "Premium collection featuring hand-stitched leather and automatic movement. Sapphire crystal display back.",
    price: 89000,
    image: "https://images.unsplash.com/photo-1548169874-53e85f753f1e?w=400&h=400&fit=crop",
    category: "Premium",
    brand: "ORON",
    inStock: false,
  },
  {
    id: "9",
    name: "High Godly Leather",
    description: "Exquisite timepiece with genuine crocodile leather strap. Features moon phase complication and power reserve indicator.",
    price: 125000,
    image: "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?w=400&h=400&fit=crop",
    category: "Luxury",
    brand: "ORON",
    inStock: true,
  },
  {
    id: "10",
    name: "Deep Frys Collection",
    description: "Vintage-inspired design with modern reliability. Features chronograph function and tachymeter bezel.",
    price: 68000,
    originalPrice: 78000,
    image: "https://images.unsplash.com/photo-1606744824163-985d376605aa?w=400&h=400&fit=crop",
    category: "Modern",
    brand: "ORON",
    inStock: true,
  },
  {
    id: "11",
    name: "Instr Bnys Edition",
    description: "Instrument-grade precision with aviation-inspired design. Luminous markers and rotating bezel.",
    price: 55000,
    image: "https://images.unsplash.com/photo-1585123334904-845d60e97b29?w=400&h=400&fit=crop",
    category: "Modern",
    brand: "ORON",
    inStock: true,
  },
  {
    id: "12",
    name: "Deep Duke Classic",
    description: "Classic Duke series with traditional Roman numerals and slim profile. Perfect for the discerning gentleman.",
    price: 72000,
    originalPrice: 85000,
    image: "https://images.unsplash.com/photo-1594534475808-b18fc33b045e?w=400&h=400&fit=crop",
    category: "Classic",
    brand: "ORON",
    inStock: true,
  },
]

export const categories = ["All", "Classic", "Modern", "Premium", "Luxury"]

export const testimonials = [
  {
    id: "1",
    name: "Sasadin",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
    rating: 5,
    text: "Great with our customer facing aspirations, who strived towards perfecting our testimonies and firm executive alignments onto sas, firmly seside and architectural satisfaction to friends.",
  },
  {
    id: "2",
    name: "Michael",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
    rating: 5,
    text: "The quality of ORON watches is unmatched. I've been wearing mine daily for 2 years and it still looks brand new. Highly recommended!",
  },
  {
    id: "3",
    name: "Chioma",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    rating: 5,
    text: "Absolutely love my ORON watch! The craftsmanship is exceptional and I receive compliments everywhere I go. Best purchase I've made.",
  },
]
